# Generated by Django 3.2.20 on 2023-07-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='definitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('shortDefinition', models.CharField(max_length=100)),
                ('longDefinition', models.CharField(max_length=300)),
            ],
        ),
    ]
