# Generated by Django 3.2.20 on 2023-07-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0003_rename_definitions_definition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definition',
            name='longDefinition',
        ),
        migrations.RemoveField(
            model_name='definition',
            name='shortDefinition',
        ),
        migrations.AddField(
            model_name='definition',
            name='long_Definition',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='definition',
            name='short_Definition',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
