# Generated by Django 3.2.20 on 2023-07-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0004_auto_20230730_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='short_Definition',
            field=models.TextField(blank=True, default=None, max_length=100),
        ),
    ]
