# Generated by Django 3.2.20 on 2023-07-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0005_alter_definition_short_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='short_Definition',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
